name: Laravel Deploy Preview
description: Deploy PR preview sites for Laravel apps.
author: Jacob Baker-Kretzmar
inputs:
  forge-token:
    description: Laravel Forge API token.
    required: true
  github-token:
    description: GitHub token to create an authenticated Octokit client.
    required: false
    default: ${{ github.token }}
  servers:
    description: 'List of Forge servers to use for deploy previews. Each line must contain a domain name and a Forge server ID separated by a space. Note: currently only supports a single server.'
    required: true
  after-deploy:
    description: Shell script to append and run after the default Forge deploy script. E.g. `npm ci && npm run build`.
    required: false
  environment:
    description: Environment variables to add or update on the preview site.
    required: false
  existing-certificate:
    description: Existing SSL certificate to use for the preview site.
    required: false
  existing-certificate-key:
    description: Existing SSL certificate private key to use for the preview site.
    required: false
  clone-certificate:
    description: Forge SSL certificate ID to clone to the preview site.
    required: false
outputs:
  site-url:
    description: 'The URL of the deployed preview site.'
  site-id:
    description: 'The Forge ID of the deployed preview site.'
runs:
  using: node20
  main: dist/index.js
