name: Deploy Preview
description: Deploy a PR preview site to Forge
inputs:
  forge-token:
    description: Laravel Forge API token
    required: true
  server:
    required: true
  domain:
    required: true
runs:
  using: node16
  main: dist/index.js
