name: Deploy Preview
description: Deploy a PR preview site to Forge.
inputs:
  forge-token:
    description: Laravel Forge API token.
    required: true
  servers:
    description: List of Forge servers to use for deploy previews.
    required: true
  after-deploy:
    description: Shell script to append and run after the default Forge deploy script. E.g. `npm ci && npm run build`.
    required: false
runs:
  using: node16
  main: dist/index.js
